name: abshires_boutique_app
description: A custom app for Abshire's Boutique.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.8.2
  firebase_storage: ^11.3.0
  stripe_payment: ^1.0.11
  google_fonts: ^6.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/