name: Upload Products to Firebase

on:
  push:
    paths:
      - 'products.json'  # Trigger the action when the products.json file is updated
    branches:
      - main  # Trigger on push to the main branch

jobs:
  upload_products:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Upload product data to Firebase
        env:
          FIREBASE_AUTH_TOKEN: ${{ secrets.FIREBASE_AUTH_TOKEN }}  # Add Firebase token to secrets
        run: |
          # Install Firebase CLI
          npm install -g firebase-tools

          # Log in to Firebase using the service account token
          firebase login --token $FIREBASE_AUTH_TOKEN

          # Upload products to Firestore
          node uploadProducts.js
